-- Seed: World Cup 2026 qualified teams (48 teams)
-- Bilingual names (English / Arabic) + flag emoji

insert into public.teams (code, name_en, name_ar, flag) values
  ('USA', 'United States', 'الولايات المتحدة', '🇺🇸'),
  ('CAN', 'Canada', 'كندا', '🇨🇦'),
  ('MEX', 'Mexico', 'المكسيك', '🇲🇽'),
  ('ARG', 'Argentina', 'الأرجنتين', '🇦🇷'),
  ('BRA', 'Brazil', 'البرازيل', '🇧🇷'),
  ('URU', 'Uruguay', 'الأوروغواي', '🇺🇾'),
  ('COL', 'Colombia', 'كولومبيا', '🇨🇴'),
  ('ECU', 'Ecuador', 'الإكوادور', '🇪🇨'),
  ('PAR', 'Paraguay', 'الباراغواي', '🇵🇾'),
  ('CHI', 'Chile', 'تشيلي', '🇨🇱'),
  ('FRA', 'France', 'فرنسا', '🇫🇷'),
  ('ENG', 'England', 'إنجلترا', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('ESP', 'Spain', 'إسبانيا', '🇪🇸'),
  ('GER', 'Germany', 'ألمانيا', '🇩🇪'),
  ('POR', 'Portugal', 'البرتغال', '🇵🇹'),
  ('ITA', 'Italy', 'إيطاليا', '🇮🇹'),
  ('NED', 'Netherlands', 'هولندا', '🇳🇱'),
  ('BEL', 'Belgium', 'بلجيكا', '🇧🇪'),
  ('CRO', 'Croatia', 'كرواتيا', '🇭🇷'),
  ('DEN', 'Denmark', 'الدنمارك', '🇩🇰'),
  ('SUI', 'Switzerland', 'سويسرا', '🇨🇭'),
  ('AUT', 'Austria', 'النمسا', '🇦🇹'),
  ('POL', 'Poland', 'بولندا', '🇵🇱'),
  ('SRB', 'Serbia', 'صربيا', '🇷🇸'),
  ('TUR', 'Turkey', 'تركيا', '🇹🇷'),
  ('NOR', 'Norway', 'النرويج', '🇳🇴'),
  ('SCO', 'Scotland', 'اسكتلندا', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  ('JPN', 'Japan', 'اليابان', '🇯🇵'),
  ('KOR', 'South Korea', 'كوريا الجنوبية', '🇰🇷'),
  ('IRN', 'Iran', 'إيران', '🇮🇷'),
  ('AUS', 'Australia', 'أستراليا', '🇦🇺'),
  ('KSA', 'Saudi Arabia', 'السعودية', '🇸🇦'),
  ('QAT', 'Qatar', 'قطر', '🇶🇦'),
  ('UAE', 'United Arab Emirates', 'الإمارات', '🇦🇪'),
  ('JOR', 'Jordan', 'الأردن', '🇯🇴'),
  ('UZB', 'Uzbekistan', 'أوزبكستان', '🇺🇿'),
  ('IRQ', 'Iraq', 'العراق', '🇮🇶'),
  ('MAR', 'Morocco', 'المغرب', '🇲🇦'),
  ('TUN', 'Tunisia', 'تونس', '🇹🇳'),
  ('ALG', 'Algeria', 'الجزائر', '🇩🇿'),
  ('EGY', 'Egypt', 'مصر', '🇪🇬'),
  ('SEN', 'Senegal', 'السنغال', '🇸🇳'),
  ('GHA', 'Ghana', 'غانا', '🇬🇭'),
  ('CIV', 'Ivory Coast', 'ساحل العاج', '🇨🇮'),
  ('NGA', 'Nigeria', 'نيجيريا', '🇳🇬'),
  ('RSA', 'South Africa', 'جنوب أفريقيا', '🇿🇦'),
  ('CMR', 'Cameroon', 'الكاميرون', '🇨🇲'),
  ('NZL', 'New Zealand', 'نيوزيلندا', '🇳🇿')
on conflict (code) do update
  set name_en = excluded.name_en,
      name_ar = excluded.name_ar,
      flag = excluded.flag;
